# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0040_alter_exercise_license_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLibraryMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise Library Metadata',
                'verbose_name_plural': 'Exercise Library Metadata',
            },
        ),
        migrations.CreateModel(
            name='ExercisePublicationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review / Community Suggestion'), ('published', 'Published'), ('archived', 'Archived / Deactivated')], db_index=True, default='published', max_length=32)),
                ('default_sets', models.IntegerField(default=3)),
                ('default_reps', models.IntegerField(default=10)),
                ('video_url', models.URLField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_exercises', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_state', to='exercises.exercise')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Publication State',
                'verbose_name_plural': 'Exercise Publication States',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Exercise Favorite',
                'verbose_name_plural': 'User Exercise Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
