# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0037_powersync_synced_ingredient_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='KineticIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, default='General', max_length=64)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('calories_kcal', models.FloatField(help_text='Calories in kcal per 100g')),
                ('protein_g', models.FloatField(help_text='Protein in grams per 100g')),
                ('carbs_g', models.FloatField(help_text='Carbohydrates in grams per 100g')),
                ('fat_g', models.FloatField(help_text='Fat in grams per 100g')),
                ('fiber_g', models.FloatField(default=0.0, help_text='Dietary fiber in grams per 100g')),
                ('sugar_g', models.FloatField(default=0.0, help_text='Sugars in grams per 100g')),
                ('sodium_mg', models.FloatField(default=0.0, help_text='Sodium in milligrams per 100g')),
                ('source', models.CharField(choices=[('local_curated', 'Local Curated Starter Dataset'), ('open_food_facts', 'Open Food Facts Live Cache'), ('user_submitted', 'User Submitted Entry')], db_index=True, default='local_curated', max_length=32)),
                ('verified', models.BooleanField(default=True, help_text='True if approved for global athlete search')),
                ('household_units', models.JSONField(blank=True, default=dict, help_text="Custom per-ingredient household unit mappings to grams (e.g. {'cup': 195.0, 'piece': 120.0})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kinetic Ingredient',
                'verbose_name_plural': 'Kinetic Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KineticDiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('quantity_g', models.FloatField(help_text='Canonical gram weight consumed')),
                ('unit_entered', models.CharField(default='g', max_length=32)),
                ('unit_quantity', models.FloatField(default=100.0)),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], db_index=True, default='lunch', max_length=16)),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='nutrition.kineticingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinetic_diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kinetic Diary Entry',
                'verbose_name_plural': 'Kinetic Diary Entries',
                'ordering': ['-logged_at'],
            },
        ),
    ]
