# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_powersync_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_admin', models.BooleanField(default=False, help_text='Explicit authorization flag required for admin API and console access.')),
                ('totp_secret', models.CharField(blank=True, default='', help_text='Base32 encoded TOTP secret for mandatory two-factor authentication.', max_length=64)),
                ('is_totp_verified', models.BooleanField(default=False, help_text='Whether 2FA device has been enrolled and verified.')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin / Gym Owner'), ('staff_coach', 'Staff Coach'), ('auditor', 'Security Auditor')], default='superadmin', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_admin_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(db_index=True, editable=False, max_length=64)),
                ('target_model', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('target_id', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.TextField(blank=True, default='', editable=False)),
                ('before_state', models.JSONField(blank=True, default=dict, editable=False)),
                ('after_state', models.JSONField(blank=True, default=dict, editable=False)),
                ('details', models.TextField(blank=True, default='', editable=False)),
                ('admin_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
