# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hrv_rmssd', models.FloatField(blank=True, help_text='Root mean square of successive RR interval differences (ms)', null=True)),
                ('resting_hr', models.FloatField(blank=True, help_text='Resting heart rate (bpm)', null=True)),
                ('sleep_duration_hrs', models.FloatField(blank=True, help_text='Total sleep duration in hours', null=True)),
                ('sleep_quality_score', models.FloatField(blank=True, help_text='Subjective/device sleep score (0-100)', null=True)),
                ('steps', models.IntegerField(blank=True, help_text='Daily step count', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Morning body weight in kilograms', null=True)),
                ('soreness_score', models.FloatField(blank=True, help_text='Subjective muscle soreness (1-10)', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Metrics',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MLDailyRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('readiness_state', models.CharField(default='Optimal Readiness', max_length=32)),
                ('action_recommendation', models.CharField(default='Train as Prescribed', max_length=64)),
                ('target_rpe', models.FloatField(default=8.0)),
                ('volume_adjustment_pct', models.IntegerField(default=0, help_text='e.g. +0%, -20%, +10%')),
                ('why_reasoning_json', models.JSONField(default=dict, help_text='Comprehensive structured reasoning backing the daily recommendation')),
                ('model_version', models.CharField(default='v1.3-composite-heuristic', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Daily Recommendation',
                'verbose_name_plural': 'ML Daily Recommendations',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MLRecoveryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.IntegerField(help_text='Recovery score (0-100)')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence based on data completeness (0.0 - 1.0)')),
                ('contributing_factors', models.JSONField(default=dict, help_text='Structured factors explaining score: hrv_delta_pct, sleep_debt_min, load_yesterday, verdict')),
                ('recovery_model_version', models.CharField(default='v1.2-stat-transparent', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Recovery Score',
                'verbose_name_plural': 'ML Recovery Scores',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MLStrengthTrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(db_index=True, max_length=128)),
                ('current_e1rm_kg', models.FloatField(help_text='Current Estimated 1RM in kg')),
                ('projected_e1rm_4w_kg', models.FloatField(help_text='Projected Estimated 1RM in 4 weeks')),
                ('rate_of_change_kg_per_week', models.FloatField(help_text='Rate of progression (kg/week)')),
                ('weeks_to_next_benchmark', models.FloatField(blank=True, help_text='Estimated weeks to target benchmark', null=True)),
                ('confidence', models.FloatField(default=0.85)),
                ('trajectory_json', models.JSONField(default=dict, help_text='Historical and projected points for chart rendering')),
                ('model_version', models.CharField(default='v1.0-theil-sen-robust', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_trajectories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Strength Trajectory',
                'verbose_name_plural': 'ML Strength Trajectories',
                'ordering': ['exercise_name'],
                'unique_together': {('user', 'exercise_name')},
            },
        ),
        migrations.CreateModel(
            name='MLTrainingLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('acute_load_7d', models.FloatField(default=0.0, help_text='7-day rolling volume/RPE fatigue load')),
                ('chronic_load_28d', models.FloatField(default=0.0, help_text='28-day rolling volume/RPE fitness load')),
                ('acwr', models.FloatField(default=1.0, help_text='Acute:Chronic Workload Ratio')),
                ('load_status', models.CharField(default='optimal', help_text='optimal (0.8-1.3), overreaching (1.3-1.5), high_injury_risk (>1.5), undertraining (<0.8)', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Training Load',
                'verbose_name_plural': 'ML Training Loads',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MLWeightTrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('current_weight_kg', models.FloatField()),
                ('ema_weight_kg', models.FloatField(help_text='Smoothed exponential moving average weight')),
                ('slope_kg_per_week', models.FloatField(help_text='Weekly rate of weight change (kg/week)')),
                ('lower_bound_kg', models.FloatField(help_text='Lower 95% confidence bound')),
                ('upper_bound_kg', models.FloatField(help_text='Upper 95% confidence bound')),
                ('trajectory_json', models.JSONField(default=dict, help_text='Series data for confidence-band chart rendering')),
                ('model_version', models.CharField(default='v1.0-ema-kalman-hybrid', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_trajectories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Weight Trajectory',
                'verbose_name_plural': 'ML Weight Trajectories',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
