# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_feedbackreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Outdoor Running'), ('walking', 'Walking / Hiking'), ('cycling', 'Cycling'), ('general_steps', 'Daily Passive Steps')], db_index=True, default='general_steps', max_length=32)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance_meters', models.FloatField(default=0.0, help_text='Total GPS distance covered in meters')),
                ('step_count', models.IntegerField(default=0, help_text='Total pedometer steps recorded')),
                ('avg_pace_min_per_km', models.FloatField(default=0.0, help_text='Average pace in minutes per km')),
                ('calories_burned', models.FloatField(default=0.0, help_text='Estimated active calories burned (kcal)')),
                ('route_geojson', models.JSONField(blank=True, default=dict, help_text='GeoJSON LineString or list of [lat, lng, altitude, timestamp] coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-start_time'],
            },
        ),
    ]
