# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0041_exercisepublicationstate_userexercisefavorite_metadata'),
        ('core', '0032_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 5-Day Hypertrophy Split', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1, help_text='Version integer to prevent rewriting mid-program history')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Schedule',
                'verbose_name_plural': 'Program Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day index (1, 2, 3, 4, 5, etc.)')),
                ('label', models.CharField(help_text='e.g. Day 1 - Push (Chest, Shoulders, Triceps)', max_length=150)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.programschedule')),
            ],
            options={
                'verbose_name': 'Program Day',
                'verbose_name_plural': 'Program Days',
                'ordering': ['day_number'],
                'unique_together': {('schedule', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=200)),
                ('target_muscle', models.CharField(blank=True, help_text='Derived from linked exercise', max_length=100)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='8-12', help_text="e.g. '8-12', '5', 'AMRAP'", max_length=32)),
                ('technique', models.CharField(choices=[('normal', 'Normal Straight Sets'), ('superset', 'Superset'), ('drop_set', 'Drop Set'), ('max', 'Max Effort (1-3RM)'), ('amrap', 'AMRAP (As Many Reps As Possible)')], default='normal', max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(help_text='Strict foreign key to shared Exercise Library', on_delete=django.db.models.deletion.CASCADE, related_name='program_prescriptions', to='exercises.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.programday')),
            ],
            options={
                'verbose_name': 'Program Exercise',
                'verbose_name_plural': 'Program Exercises',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('membership_start_date', models.DateField(default=django.utils.timezone.now)),
                ('membership_end_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_clients', to='core.programschedule')),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Membership',
                'verbose_name_plural': 'Client Memberships',
                'ordering': ['membership_end_date'],
            },
        ),
        migrations.CreateModel(
            name='BodyStatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('recorded_by_type', models.CharField(choices=[('admin', 'Gym Owner / Trainer In-Person Check-In'), ('client_self', 'Athlete Self-Logged')], db_index=True, default='admin', max_length=32)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('shoulder_cm', models.FloatField(blank=True, null=True)),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('arm_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('hip_cm', models.FloatField(blank=True, null=True)),
                ('thigh_cm', models.FloatField(blank=True, null=True)),
                ('calf_cm', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text="Açıklama / Context description e.g. 'Before starting program'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_stat_entries', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_body_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Body Stat Entry',
                'verbose_name_plural': 'Body Stat Entries',
                'ordering': ['-recorded_date', '-created_at'],
            },
        ),
    ]
