# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_gym_admin_panel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programday',
            options={'ordering': ['order', 'day_number'], 'verbose_name': 'Program Day', 'verbose_name_plural': 'Program Days'},
        ),
        migrations.AddField(
            model_name='programday',
            name='order',
            field=models.IntegerField(default=0, help_text='Explicit sequence position'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='rest_seconds',
            field=models.IntegerField(default=90, help_text='Prescribed rest interval in seconds'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='target_weight_kg',
            field=models.FloatField(default=0.0, help_text='Canonical weight-based prescription in kilograms'),
        ),
        migrations.CreateModel(
            name='GymOwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(help_text='e.g. Kinetic Performance Lab', max_length=150)),
                ('gym_id', models.CharField(db_index=True, default='default_gym', max_length=64)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Must be approved by operator/verified owner')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_owners', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Owner Profile',
                'verbose_name_plural': 'Gym Owner Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
