# Generated by Django on 2026-08-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_gym_command_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.IntegerField(default=20)),
                ('seats_reserved', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('tombstone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gym Class',
                'verbose_name_plural': 'Gym Classes',
            },
        ),
        migrations.CreateModel(
            name='GymClassBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('tombstone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.gymclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Class Booking',
                'verbose_name_plural': 'Gym Class Bookings',
            },
        ),
        migrations.CreateModel(
            name='SyncChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('op', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('client_version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_changelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Change Log',
                'verbose_name_plural': 'Sync Change Logs',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='syncchangelog',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='core_syncch_entity__2e6462_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchangelog',
            index=models.Index(fields=['processed', 'created_at'], name='core_syncch_process_f91535_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchangelog',
            index=models.Index(fields=['id', 'created_at'], name='core_syncch_id_0bc9f7_idx'),
        ),
    ]
