# Generated by Django 6.0.8 on 2026-08-20 06:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_sync_changelog_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable slug; changing this breaks existing UserAchievements', max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('rule_type', models.CharField(choices=[('workout_count', 'Workout Count'), ('streak_days', 'Streak Days'), ('benchmark_hit', 'Benchmark Hit'), ('class_attended', 'Class Attended'), ('nutrition_streak', 'Nutrition Streak'), ('body_goal', 'Body Goal')], max_length=24)),
                ('threshold', models.PositiveIntegerField(default=1, help_text='e.g. 10 workouts, 7-day streak, etc.')),
                ('icon_url', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rule_type', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=12)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, help_text='Null when status=booked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('workout', 'Workout'), ('program', 'Program'), ('exercise', 'Exercise'), ('trainer', 'Trainer')], max_length=12)),
                ('entity_id', models.CharField(help_text='UUID or PK string of the favorited entity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.CharField(db_index=True, default='default_gym', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_lat', models.FloatField(blank=True, help_text='Real GPS latitude — never mocked', null=True)),
                ('venue_lng', models.FloatField(blank=True, help_text='Real GPS longitude — never mocked', null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE string for recurring classes', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HomeWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('recovery_score', 'Recovery Score'), ('next_class', 'Next Class'), ('streak', 'Streak'), ('weekly_volume', 'Weekly Volume'), ('steps', 'Steps'), ('sleep', 'Sleep'), ('weight', 'Weight'), ('training_load', 'Training Load')], max_length=24)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Explicit position; never inferred from array index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('online_workout', 'Online Workout'), ('nutrition_consultation', 'Nutrition Consultation')], max_length=32)),
                ('requested_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('payment_ref', models.CharField(blank=True, help_text='Opaque payment-provider token — never raw card data', max_length=200)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.CharField(db_index=True, default='default_gym', max_length=64)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('specialties', models.JSONField(default=list, help_text='List of specialty strings')),
                ('certifications', models.JSONField(default=list, help_text='List of certification strings')),
                ('media_urls', models.JSONField(default=list, help_text='Profile/banner image relative paths')),
                ('is_accepting_bookings', models.BooleanField(default=False, help_text='Set by gym owner, not self')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='core_syncch_entity__68fc76_idx',
            old_name='core_syncch_entity__2e6462_idx',
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='core_syncch_process_ed262f_idx',
            old_name='core_syncch_process_f91535_idx',
        ),
        migrations.RenameIndex(
            model_name='syncchangelog',
            new_name='core_syncch_id_d80429_idx',
            old_name='core_syncch_id_0bc9f7_idx',
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='order',
            field=models.IntegerField(default=0, help_text='Explicit sequence position'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.groupclass'),
        ),
        migrations.AddField(
            model_name='homewidget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatesession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='private_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.privatesession'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatesession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to='core.trainerprofile'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_classes', to='core.trainerprofile'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='core.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'entity_type'], name='core_favori_user_id_b34544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'entity_type', 'entity_id')},
        ),
        migrations.AddIndex(
            model_name='homewidget',
            index=models.Index(fields=['user', 'position'], name='core_homewi_user_id_21067c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='homewidget',
            unique_together={('user', 'widget_type')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_ref__isnull', False), ('private_session__isnull', True)), models.Q(('class_ref__isnull', True), ('private_session__isnull', False)), _connector='OR'), name='booking_exactly_one_ref'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('class_ref', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupclass',
            index=models.Index(fields=['gym_id', 'status', 'start_time'], name='core_groupc_gym_id_acd6c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
